/** Motion / distortion knobs for featured-work image planes (desktop). */
export const FEATURED_IMAGE = {
  PARALLAX_FACTOR: 1.2,
  SCROLL_VELOCITY_SCALE: 8e-4,
  SCROLL_IMPULSE_SCALE: 0.008,
  PLANE_SEGMENTS_X: 32,
  PLANE_SEGMENTS_Y: 10,
  BARREL_SCALE: 0.32,
  BARREL_EDGE_LIFT: 0.25,
  BARREL_ATTACK_LERP: 0.06,
  BARREL_RELEASE_LERP: 0.035,
  BARREL_VELOCITY_THRESHOLD: 0.012,
  BARREL_SPEED_FACTOR: 0.18,
  BARREL_IMPULSE_FACTOR: 1.8,
  BARREL_MAX_STRENGTH: 1,
  GRID_SIZE: 12,
  GRID_MOUSE_RADIUS: 0.1,
  GRID_STRENGTH: 0.15,
  GRID_RELAXATION: 0.9,
  GRID_UV_DISTORT: 0.02,
  /** CSS parallax fallback below tablet-landscape. */
  MOBILE_Y_PERCENT: 14,
  MOBILE_SCALE: 1.2,
} as const;
